// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Taxi_NET_API.Data;

#nullable disable

namespace TaxiNETAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Taxi_NET_API.Models.TaxiDriver", b =>
                {
                    b.Property<int>("TaxiDriverID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TaxiDriverID"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<bool>("IsManualLicence")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("XCoordinates")
                        .HasColumnType("int");

                    b.Property<int>("YCoordinates")
                        .HasColumnType("int");

                    b.HasKey("TaxiDriverID");

                    b.ToTable("TaxiDrivers");
                });
#pragma warning restore 612, 618
        }
    }
}
